#+title: Dotfiles and System Configuration

* Summary

This is my dotfiles directory containing all my personalized system configuration for Linux (Ubuntu).

The setup is as follows:
- Clone the repo into a ".dotfiles" folder in your home folder.
- Run the setup-linux.sh script.

#+begin_src shell
git clone https://github.com/YaBoich/dotfiles .dotfiles/
cd .dotfiles/
bash setup-linux.sh
#+end_src

* Setup

** WSL Ubuntu

To create a fresh install using Windows Subsystem for Linux and Ubuntu.

- Download Ubuntu from the Windows Store if you haven't already.
- If you have an existing WSL instance and want to get rid of it. Do this in your Window's Powershell:

  #+begin_src powershell
  wsl --list
  wsl --unregister Ubuntu
  #+end_src

  (Replace "Ubuntu" with the name of the instance you want to get rid of.
- Open Ubuntu again, it will install, then clone this repo into ".dotfiles" and run the setup script.

* Symlinks

Symbolic links are created for configuration that is supposed to live in the home directory. Such as:

#+begin_src shell
ln -s ~/.dotfiles/emacs/ ~/.emacs.d

# Can view symlinks with:
ls -la ~ | grep .emacs.d

# Or all in a directory with 
ls -la
#+end_src

* Helpful Information

** Github Credentials

The easiest way to store github credentials is to generate a classic token and then run the following in a repo:

#+begin_src shell
git config --global user.email "email here"
git config --global user.name "name here"
git config credential.helper store
git push
$Username: <your username>
$Password: <the access token>
#+end_src

The token will now be stored in plaintext in your root directory under .git-credentials 

Obviously this will be in plain text and is not recommened for important keys. Use with discretion.
